title: Data Analytics
description: Data Analytics
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
    title: Learning
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
